[package]
name = "logo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13"
clap = "2.33"
svg = "0.14.0"
rand = "0.8.5"
# nom = "7.1.3"